### ISSUE TITLE
ES2017 (ES8) 소개 (Introduce ECMAScript® 2017 Language Specification)

### ISSUE THREAD

**Issue by ragingwind** [seouljs/meeting#15]
스피커: 윤병준(@onyoon7)
참고자료: 
- https://www.ecma-international.org/publications/standards/Ecma-262.htm
- https://hackernoon.com/es8-was-released-and-here-are-its-main-new-features-ee9c394adf66
시간 : 30분
형태 : 프리젠테이션
대상 : 자바스크립트를 트렌디하게 써보고 싶은 분 & ES8에는 뭐가 들어있나 궁금하신 분

**Comment by rhiokim** [comment]
막! '이 주제를 등록해야지' 라고 생각하고 왔는데 똭! 있네요. 👍

**Comment by onyoon7** [comment]
스피커: 윤병준( @onyoon7)
참고자료: 
- https://www.ecma-international.org/publications/standards/Ecma-262.htm
- https://hackernoon.com/es8-was-released-and-here-are-its-main-new-features-ee9c394adf66
시간 : 30분
형태 : 프리젠테이션
대상 : 자바스크립트를 트렌디하게 써보고 싶은 분 & ES8에는 뭐가 들어있나 궁금하신 분

**Comment by ragingwind** [comment]
@onyoon7 Updated

**Comment by onyoon7** [comment]
**[발표자 소개]**
비전공자로 프로그래밍 부트캠프를 통해 개발을 시작하여, Angular 로컬라이제이션과 ’국민투표로또’ 프로젝트를 리딩하였다. 현재는 React/Redux를 이용하여 E-commerce 쇼핑몰을 만들고 있다. 자바스크립트의 기본과 프레임워크의 발전에 관심이 많으며, 기술을 통해 조금이나마 세상에 선한 영향력을 끼치고 싶은 소망을 품고 있다.

**[발표내용]**
자바스크립트의 표준이라고 할 수 있는 ECMAScript는 7년만에 발표한 2015년의 ES6를 시작으로 매년 새로운 버전을 출시되고 있습니다. 올해도 어김없이 새로운 버전의 ECMAScript가 발표되었습니다. 지난 6월에 릴리즈된 ECMAScript 2017(ES8)에 어떤 기능(feature)이 추가되었는지 살펴보고, 이전의 ECMAScript에 있던 유사한 기능과는 어떤 차이점이 있는지 비교해 보려고 합니다.

**Comment by onyoon7** [comment]
[2017.08.18] Seoul.js 발표자료 : http://slides.com/onyoon7/ecmascript2017
