### ISSUE TITLE
일렉트론에서 자바스크립트 소스 코드 보호하기 (Protecting Javascript Source Code in Electron)

### ISSUE THREAD

**Issue by 2woongjae** [seouljs/meeting#8]
[개요, 설명, 왜, 무엇때문에]

- 스피커 : Mark
- 형태 : 프리젠테이션 & 라이브코딩
- 참고자료 : 
  - http://enclosejs.com/
  - https://github.com/zeit/pkg
  - V8 Snapshot
- 대상[옵션] : Electron 쓰고 싶거나 쓰고 있는데, 소스 공개 문제로 고민 중인 분들

**Comment by rhiokim** [comment]
자바스크립트를 넣는게 좀 더 정확하고 일렉트론을 모르더라도 관심을 갖게 될것 같아서 살짝 변경했습니다.

**Comment by ragingwind** [comment]
이건 일렉트론에서 배포와 함께 가장 핫한 이슈인 것 같아요.

**Comment by 2woongjae** [comment]
발표자 소개
Node-Webkit 부터 시절부터 웹기술로 데스크탑 어플리케이션을 만들었다. 일렉트론과 NW.JS 를 사용하여 가상터치 솔루션을 적용한 스마트 티비, 스마트 홈 및 디지털 사이니지용 소프트웨어를 만들었다. 현재는 TypeScript 와 Electron 을 이용하여, 디자이너를 위한 인터렉션 프로토타이핑 툴인 프로토파이를 만들고 있다. 대규모 자바스크립트 어플리케이션 개발에 대한 더 나은 방향을 고민하고, 적용하기 위해 노력하고 있다.

**Comment by 2woongjae** [comment]
발표내용
일렉트론을 프로덕션 레벨에서 사용하기 위해, 비지니스 로직에 대한 소스 보호가 필요합니다.
일렉트론 자체적으로 제공하는 방법은 없기 때문에 우회해서 보호를 해야합니다.
상용 프로그램인 프로토파이에서 소스를 보호한 방법을 소개하고,
간단하게 소스가 보호된 일렉트론 앱을 만들어보겠습니다.

**Comment by 2woongjae** [comment]
발표자료 입니다.
http://slides.com/woongjae/protecting-javascript-source-code-in-electron#/
